name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # specify your .NET version here
    
    - name: Restore dependencies
      run: dotnet restore "./Heat Utility System/HUS/HUS.sln"
    
    - name: Build
      run: dotnet build "./Heat Utility System/HUS/HUS.sln" --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test "./Heat Utility System/HUS.Tests/HUS/HUS.Tests.csproj" --no-build --verbosity normal
